version: '3.8'
services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    container_name: frontend
    restart: always

  api:
    build:
      context: api
    volumes:
      - db-data:/app/database
    user: root
    ports:
      - "8080:8080"
    container_name: api
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
    container_name: nginx
    restart: always

  rfid:
    build:
      context: rfid
    privileged: true
    container_name: rfid
    restart: always

volumes:
  db-data: